server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.15.0"
      snapshot: false
  server:
    password: "youshallnotpass"
    sources:
      youtube: false  # IMPORTANT: Désactiver l'ancienne source
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""

logging:
  file:
    path: ./logs/

  level:
    root: INFO
    lavalink: INFO

  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - TVHTML5
      - WEB_REMIX
      - ANDROID
    # IMPORTANT: Utiliser yt-dlp comme fallback
    youtubeConfig:
      TVHTML5:
        playback: true
      WEB_REMIX:
        playback: true
      ANDROID:
        playback: true
    # Activer yt-dlp pour la récupération des formats
    yt-dlp:
      enabled: true